name: notify-build-status
description: "Notify the release status"

inputs:
  vaultUrl:
    description: Vault URL
    required: true
  vaultRoleId:
    description: Vault role ID
    required: true
  vaultSecretId:
    description: Vault secret ID
    required: true
  slackChannel:
    description: Slack channel
    required: false

runs:
  using: composite
  steps:
    - name: Get the Slack token from Vault
      uses: hashicorp/vault-action@v2.4.2
      with:
        url: ${{ inputs.vaultUrl }}
        roleId: ${{ inputs.vaultRoleId }}
        secretId: ${{ inputs.vaultSecretId }}
        method: approle
        secrets: |
          secret/observability-team/ci/stack-integartion-token integration_token | SLACK_BOT_TOKEN
    - name: Prepare outputs
      id: prepare
      shell: python
      run: |
        import os
        
        # Keys taken from https://docs.github.com/en/actions/learn-github-actions/contexts#job-context
        color_status_map = {
          "success": "good",
          "failure": "danger",
          "cancelled": "", # grey
        }
                
        data = {
          "color": color_status_map["${{ job.status }}"],
          "short_sha": "${{ github.event.pull_request.head.sha }}"[:7] if "${{ github.event_name }}" == 'pull_request' else "${{ github.sha }}"[:7],
          "commit_url": "${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.pull_request.number }}/commits/${{ github.sha }}" if "${{ github.event_name }}" == 'pull_request' else "${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}",
          "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}",
        }
        
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            for key, value in data.items():
              print(f'{key}={value}', file=f)

    - uses: slackapi/slack-github-action@v1.22.0
      with:
        channel-id: '${{ inputs.slackChannel }}'
        payload: |
          {
            "attachments": [
              {
                "pretext": "Workflow <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}> triggered by <${{ github.server_url}}/${{ github.actor }}|${{ github.actor }}>",
                "color": "${{ steps.prepare.outputs.color }}",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "${{ job.status }}"
                  },
                  {
                    "title": "Event",
                    "short": true,
                    "value": "${{ github.event_name	}}"
                  },
                  {
                    "title": "Ref",
                    "short": true,
                    "value": "${{ github.ref_name }}"
                  },
                  {
                    "title": "Commit",
                    "short": true,
                    "value": "<${{ steps.prepare.outputs.commit_url }}|`${{ steps.prepare.outputs.short_sha }}`>"
                  },
                  {
                    "title": "Workflow",
                    "short": false,
                    "value": "<${{ steps.prepare.outputs.run_url }}|${{ github.workflow }} #${{ github.run_number }}>"
                  }
                ],
                "footer": "<${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>",
                "footer_icon": "https://slack-imgs.com/?c=1&o1=wi32.he32.si&url=https%3A%2F%2Fslack.github.com%2Fstatic%2Fimg%2Ffavicon-neutral.png"
              }
            ]
          }
