name: notify-release
description: "Notify the release status"

inputs:
  vaultUrl:
    description: Vault URL
    required: true
  vaultRoleId:
    description: Vault role ID
    required: true
  vaultSecretId:
    description: Vault secret ID
    required: true
  slackChannel:
    description: Slack channel
    required: false

runs:
  using: composite
  steps:
    - name: Get the Slack token from Vault
      uses: hashicorp/vault-action@v2.4.2
      with:
        url: ${{ inputs.vaultUrl }}
        roleId: ${{ inputs.vaultRoleId }}
        secretId: ${{ inputs.vaultSecretId }}
        method: approle
        secrets: |
          secret/observability-team/ci/stack-integartion-token integration_token | SLACK_BOT_TOKEN
    - name: Prepare outputs
      id: prepare
      shell: python
      run: |
        import os
        
        color_status_map = {
          "success": "good",
          "failure": "danger,
        }
        
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            print(f'color={color_status_map['${{ job.status}}']}', file=f)

    - uses: slackapi/slack-github-action@v1.22.0
      with:
        channel-id: '${{ inputs.slackChannel }}'
        payload: |
          {
            "attachments": [
              {
                "pretext": "${{ github.repository }} release ${{ github.ref_name }}",
                "color": "${{ steps.prepare.outputs.color }}",
                "fields": [
                  {
                    "title": "Status",
                    "short": true,
                    "value": "${{ job.status }}"
                  },
                  {
                    "title": "Ref",
                    "short": true,
                    "value": "${{ github.ref_name }}"
                  },
                  {
                    "title": "Commit",
                    "short": true,
                    "value": "${{ github.sha }}"
                  }
                ],
                "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>",
                "footer_icon": "https://slack-imgs.com/?c=1&o1=wi32.he32.si&url=https%3A%2F%2Fslack.github.com%2Fstatic%2Fimg%2Ffavicon-neutral.png"
              }
            ]
          }
