name: completed

on:
  workflow_run:
    branches-ignore:
      - main
    types:
      - completed
    workflows:
      - heavy-test

jobs:
  heavy-test:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
      pull-requests: write
    steps:
      - name: Download artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: >
          gh run download ${{ github.event.workflow_run.id }}
          --name pr_num
          --repo "${GITHUB_REPOSITORY}" 
      - run: echo "pr_num=$(cat pr_num.txt)" >> $GITHUB_ENV
      - name: set status
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: process.env.pr_num,
              body: "Hello from GitHub Actions"
            });
