name: post-test

on:
  workflow_run:
    workflows:
      - test
    types:
      - completed
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.workflow_run.conclusion }}"
