name: post-test

on:
  workflow_run:
    workflows:
      - test
    types:
      - completed

jobs:
  post-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.workflow_run.conclusion }}"
