name: heavy-test

on:
  issue_comment:
    types:
      - created

jobs:
  heavy-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment, '/test')}}
    steps:
      - run: echo '${{ toJSON(github.event) }}'
      - run: echo "Hello"
