name: heavy-test

on:
  issue_comment:
    types:
      - created

jobs:
  heavy-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/test')}}
    steps:
      - run: echo '${{ toJSON(github.event) }}'
      - run: echo "Hello"
      - run: echo '${{ secrets.FAKE_SECRET }}'
      - name: set status
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo  
            const pullRequest = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: context.issue.number,
            });
            const sha = pullRequest.data.head.sha
            
            console.log(context)g

#            githu.rest.repos.createCommitStatus({
#              owner,
#              repo,
#              sha,
#              state,
#              status: "success"
#              context:
#            });
