name: push

on: workflow_dispatch

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/github-token@main
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
      - uses: elastic/apm-pipeline-library/.github/actions/setup-git@current
        with:
          username: ${{ env.GIT_USER }}
          email: ${{ env.GIT_EMAIL }}
          token: ${{ env.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - run: echo "Hello $(date +%s)" >> world.txt
      - run: git add world.txt
      - run: git commit -am helloworld
      - run: git push
