name: tagger

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git tag "test-$(git rev-parse --short HEAD)"
      - run: git push --tags
