name: test

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "junit-example.xml"
