name: test

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./foo
    steps:
      - uses: actions/checkout@v3
      - run: pwd
      - run: cat bar.txt
      - run: exit 1;
      - if: success()
        run: echo "Success"
      - if: failure()
        run: echo "Failure"
