name: test

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: lts
      - uses: reakaleek/apm-pipeline-library/.github/actions/setup-npmrc@feature/setup-npmrc-action
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
      - run: npm whoami
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: workflows
          path: .github/
      - run: echo "hello"
      - run: exit 1;
        continue-on-error: true
      - run: ls
      - run: echo "okay" > ok.txt
      - uses: actions/upload-artifact@v3
        with:
          name: hello
          path: ok.txt
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "**/junit-example.xml"
  ok:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: workflows
      - run: ls -ll
