name: test

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./foo
    steps:
      - run: pwd
      - run: cat bar.txt
      - run: cat bar.txt
