name: test

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  create-matrix:
    name: Create Matrix
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.create-matrix.outputs.include }}
    steps:
      - uses: actions/checkout@v3
      - run: pip install pyyaml
      - name: Create Matrix
        id: create-matrix
        shell: python
        run: |
          import os
          import json
          import yaml
          
          class Image():
            def __init__(self, name, push=True):
              self.name = name
              self.push = push
          
          images = []
          with open("images.yml", "r") as stream:
            images.extend(yaml.safe_load(stream)['images'])
          
          images_json = json.dumps([Image(image['name'], image['push'] if 'push' in image else True) for image in images])
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            print(f'include={images_json}', file=f)

  test:
    runs-on: ubuntu-latest
    needs: create-matrix
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.create-matrix.outputs.include) }}
    steps:
      - run: echo "${{ matrix.push }}"
      - if: ${{ matrix.push == '' || matrix.push == true }}
        run: exit 1
