name: test

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to test'
        required: true
        default: reakaleek/actions-playground
      ref:
        description: 'SHA to test'
        required: true
        default: ~

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
          repository: ${{ github.event.inputs.repository }}
      - run: |
          echo "Test"
