on:
  push:
    branches:
      - main

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p a/b/c
      - run: echo "hello" > a/b/c/d.txt
      - uses: actions/upload-artifact@v3
        with:
          name: abc
          path: ./a/
          if-no-files-found: error
  read:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: test
      - run: cat a/b/c/d.txt
