name: test

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  ruby:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6
    steps:
      - run: git --version
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: workflows
          path: .github/
      - run: echo "hello"
      - run: exit 1;
        continue-on-error: true
      - run: ls
      - run: echo "okay" > ok.txt
      - uses: actions/upload-artifact@v3
        with:
          name: hello
          path: ok.txt
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "**/junit-example.xml"
  ok:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: workflows
      - run: ls -ll
