name: test

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to test'
        required: true
        default: ${{ github.repository }}
      sha:
        description: 'SHA to test'
        required: true
        default: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.sha }}
          repository: ${{ github.event.inputs.repository }}
      - run: |
          echo "Test"
