on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          import requests
          response = requests.get('https://www.google.com')
          print(response)
        shell: python
