name: test

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello"
      - run: ls
      - run: echo "okay" > ok.txt
      - uses: actions/upload-artifact@v3
        with:
          name: hello
          path: ok.txt
      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: "**/junit-example.xml"
