name: test

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  test:
    defaults:
      run:
        working-directory: foo

    steps:
      - run: cat bar.txt
      - run: cat bar.txt
