on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: python --version
      - run: |
          import sys
          print(sys.version)
        shell: python
