name: test

on:
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.sha }}
      - run: echo '${{ toJSON(github.event.pull_request) }}'
      - run: echo '${{ toJSON(github.event.pull_request.sha) }}'
